# GENERATED by scripts/gen_models.sh from spec/openapi.yaml — do not hand-edit.

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class JobStatus(Enum):
    queued = 'queued'
    running = 'running'
    succeeded = 'succeeded'
    canceling = 'canceling'
    canceled = 'canceled'
    failed = 'failed'
    expired = 'expired'


class OutputType(Enum):
    image = 'image'
    video = 'video'
    audio = 'audio'
    text = 'text'
    file = 'file'
    latent = 'latent'


class Asset(BaseModel):
    id: Annotated[
        str,
        Field(description='Durable asset UUID (the value referenced from workflows).'),
    ]
    hash: Annotated[
        str | None,
        Field(description='Server-computed blake3, lazily populated; may be null.'),
    ] = None
    size_bytes: int
    content_type: str
    file_path: str | None = None
    created_new: Annotated[
        bool, Field(description='True for a brand-new blob, false for a dedup hit.')
    ]
    created_at: AwareDatetime
    url: str
    url_expires_at: AwareDatetime


class Progress(BaseModel):
    value: Annotated[
        float, Field(description='Server-computed overall fraction (0..1).')
    ]
    nodes_done: int
    nodes_total: int
    current_node: str | None = None
    current_node_class: str | None = None
    step: int | None = None
    steps: int | None = None
    message: str | None = None


class Output(BaseModel):
    node_id: str
    name: str
    type: OutputType
    content_type: str
    size_bytes: int
    id: str
    hash: str | None = None
    url: str
    url_expires_at: AwareDatetime


class JobError(BaseModel):
    code: str
    message: str
    node_id: str | None = None
    class_type: str | None = None
    traceback: str | None = None


class JobUrls(BaseModel):
    self: str
    events: str
    cancel: str


class Job(BaseModel):
    id: str
    status: JobStatus
    created_at: AwareDatetime
    started_at: AwareDatetime | None = None
    completed_at: AwareDatetime | None = None
    expires_at: AwareDatetime
    queue_position: int | None = None
    progress: Progress | None = None
    outputs: list[Output]
    error: JobError | None = None
    metrics: dict[str, int | None] | None = None
    urls: JobUrls


class AssetReferenceInfo(BaseModel):
    id: Annotated[str, Field(description='Authoritative asset UUID.')]
    hash: Annotated[
        str | None, Field(description='blake3 dedup / cross-surface lookup hint.')
    ] = None
    file_path: Annotated[
        str | None,
        Field(description='Preserves the extension for nodes that sniff it.'),
    ] = None


class AssetReference(BaseModel):
    """
    The `core/ASSET` object placed into workflow JSON where a filename would go.
    """

    field__type: Annotated[Literal['core/ASSET'], Field(alias='__type')]
    info: AssetReferenceInfo


class AssetUploadForm(BaseModel):
    file: bytes
    content_type: str
    file_path: str
    expected_hash: Annotated[
        str | None,
        Field(
            description='Optional; verified against the server-computed blake3, never trusted.'
        ),
    ] = None
    tags: list[str] | None = None


class AssetFromHashRequest(BaseModel):
    hash: str
    file_path: str | None = None
    tags: list[str] | None = None


class JobSubmitRequest(BaseModel):
    workflow: Annotated[
        dict[str, Any], Field(description='API-format workflow graph, verbatim.')
    ]


class Error(BaseModel):
    code: str
    message: str
    details: dict[str, Any] | None = None


class ErrorEnvelope(BaseModel):
    error: Error


class StatusEventData(BaseModel):
    status: JobStatus
    queue_position: int | None = None


class ProgressEventData(RootModel[Progress]):
    root: Progress


class PreviewEventData(BaseModel):
    node_id: str
    content_type: str
    data_base64: str


class OutputEventData(RootModel[Output]):
    root: Output


class LogEventData(BaseModel):
    level: str
    message: str
