#!/usr/bin/env python3
"""Fail if the committed comfy_low models drift from spec/openapi.yaml.

Regenerates the models into a temp file and diffs against the committed one. CI
runs this so a spec edit without a regen (or a hand-edit of the generated file)
is caught. Mirrors the codegen-freshness gate other repos enforce.
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COMMITTED = ROOT / "src" / "comfy_low" / "models" / "_generated.py"


def _generate(out: Path) -> None:
    subprocess.run(
        [
            "datamodel-codegen",
            "--input",
            str(ROOT / "spec" / "openapi.yaml"),
            "--input-file-type",
            "openapi",
            "--output",
            str(out),
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--target-python-version",
            "3.10",
            "--use-standard-collections",
            "--use-union-operator",
            "--use-schema-description",
            "--field-constraints",
            "--collapse-root-models",
            "--use-annotated",
            "--disable-timestamp",
            "--custom-file-header",
            "# GENERATED by scripts/gen_models.sh from spec/openapi.yaml — do not hand-edit.",
        ],
        check=True,
    )


def main() -> int:
    if not COMMITTED.exists():
        print("ERROR: committed models missing; run scripts/gen_models.sh", file=sys.stderr)
        return 1
    with tempfile.TemporaryDirectory() as td:
        fresh = Path(td) / "_generated.py"
        _generate(fresh)
        if fresh.read_text() != COMMITTED.read_text():
            print(
                "ERROR: comfy_low models are stale.\n"
                "Run scripts/gen_models.sh and commit src/comfy_low/models/_generated.py.",
                file=sys.stderr,
            )
            return 1
    print("OK: comfy_low models are in sync with spec/openapi.yaml")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
