#!/usr/bin/env bash
# Regenerate the comfy_low pydantic v2 models from the vendored spec.
# The generated file is committed; CI runs this and fails if the tree drifts.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/src/comfy_low/models/_generated.py"

datamodel-codegen \
  --input "$ROOT/spec/openapi.yaml" \
  --input-file-type openapi \
  --output "$OUT" \
  --output-model-type pydantic_v2.BaseModel \
  --target-python-version 3.10 \
  --use-standard-collections \
  --use-union-operator \
  --use-schema-description \
  --field-constraints \
  --collapse-root-models \
  --strict-nullable \
  --use-annotated \
  --disable-timestamp \
  --custom-file-header "# GENERATED by scripts/gen_models.sh from spec/openapi.yaml — do not hand-edit."

echo "Wrote $OUT"
